include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: warning
    missing_return: warning
    unused_import: info
    unused_element: ignore
  exclude:
    - "bin/cache/**"
    - "*.g.dart"
    - "lib/**/*.g.dart"
    - "*.freezed.dart"
    - "lib/**/*.freezed.dart"

linter:
  rules:
    avoid_types_on_closure_parameters: false
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    package_api_docs: true
    package_prefixed_library_names: true
    test_types_in_equals: true
    throw_in_finally: true
    unawaited_futures: false
    unnecessary_brace_in_string_interps: false
    unnecessary_breaks: true
    unnecessary_statements: true
    unnecessary_string_interpolations: false
    use_super_parameters: true
